local function copyResource(file)
	path = quarto.utils.resolvePath(file)
	quarto.doc.addFormatResource(path)
end

function Header(el)
	copyResource("assets/")

	if not el.attributes["background-image"] then
		if el.level == 1 then
			el.attributes["background-image"] = "assets/background_section_blank.jpg"
			el.attributes["background-size"] = "contain"
		elseif el.level == 2 then
			el.attributes["background-image"] = "assets/background_slide.png"
			el.attributes["background-size"] = "contain"
		end
	end

	return el
end

-- The `toc: true` slide is generated by Quarto rather than written as a
-- Header, so give it the slide background from the browser instead. (`toc`
-- is consumed as a format option and is not visible here, so the script
-- always ships and does nothing when there is no TOC slide.)
function Pandoc(doc)
	copyResource("assets/")
	quarto.doc.include_text("after-body", [[
<script>
(function () {
  var toc = document.querySelector('.reveal .slides section#TOC');
  if (!toc || toc.hasAttribute('data-background-image')) return;
  toc.setAttribute('data-background-image', 'assets/background_slide.png');
  toc.setAttribute('data-background-size', 'contain');
  if (Reveal.isReady()) Reveal.sync(); else Reveal.on('ready', function () { Reveal.sync(); });
})();
</script>
]])
	return doc
end
